config/routes.rb
Rails.application.routes.draw do
  
  get 'about_us', to: "about_us#show"
  
  # upload
  match 'admin/drinks', via: [:get, :post]
  match 'admin/speakers', via: [:get, :post]


  # event
  post 'event/create'

  get 'event/update/:id/:step', to: "event#update_get"
  patch 'event/update/:id',     to: "event#update_patch"

  get 'event/view/:id',         to: "event#read"
  delete 'event/delete/:id',    to: "event#delete"

  post 'event/payment',        to: "event#payment"

  # user
  get 'user/cancel_event/:id', to: "user#cancel_event"
  get 'user/profile_page', as: :get_profile




  # steps
  namespace :steps do    
    # get 'step1_speakers', as: :get_speakers
    match 'step1_speakers', as: :get_speakers, via: [:get, :post]

    get 'step2_drinks', as: :get_drinks
    get 'step3_total', as: :get_total
    get 'step5_location', as: :get_location
    get 'step6_review', as: :get_review
    get 'step7_payment', as: :get_payment
    get 'step8_confirmation', as: :get_confirmation
  end

  root 'application#homepage'
  
  # devise routes
  devise_for :users, path: '', 
    controllers: { registrations: 'auth/registrations' }, 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'logout', 
      password: 'password', 
      confirmation: 'confirmation', 
      unlock: 'unlock', 
      registration: 'register', 
      sign_up: 'join' }
    
  
  # add a GET logout
  devise_scope :user do
    get 'logout', to: 'devise/sessions#destroy'
    get 'profile/edit', to: 'devise/registrations#edit', as: :get_profile_edit
    get 'steps/step4_login_register'=> 'auth/register#step4_login_register', as: :steps_get_logged_in
    post 'steps/step4_login'=> 'auth/login#create', as: :post_auth_login
    post 'steps/step4_register'=> 'auth/register#create', as: :post_auth_register
    post 'password-level'=> 'auth/register#password_meter', as: :post_auth_password_level
        
    # redirection links alias
    get 'steps/step4_login'=> 'auth/register#step4_login_register'
    get 'steps/step4_register'=> 'auth/register#step4_login_register'
  end
  
  # redirect all missing path to home
  get "*path", to: redirect('/')

end

app/controllers/steps_controller.rb
#require '/Users/abudu_h/Documents/_business/watts_n_shots/code/watts_n_shots/lib/wattsnshots/utils.rb'

class StepsController < ApplicationController
  
  before_action :authenticate_user!, :only => [:step5_location, :step6_payment,
    :step7_review, :step8_confirmation]
  protect_from_forgery prepend: true, :only => [:step5_location, :step6_payment,
    :step7_review, :step8_confirmation]
  
  def step1_speakers
    puts "StepsController > step1_speakers | data: #{request.body.to_s}"

    _data = WattsNShots::Utils.get_speaker_data.to_json.to_s.html_safe

    render locals: {is_user_logged_in: user_signed_in?, data: _data, current_page: "step_1", event_id: nil}
  end
  
  def step2_drinks

    _data = WattsNShots::Utils.get_drinks_data.to_json.to_s.html_safe

    render locals: {is_user_logged_in: user_signed_in?, data: _data, current_page: "step_2"}
  end
  
  def step3_total

    render locals: {is_user_logged_in: user_signed_in?, current_page: "step_3"}
  end
  
  def step4_login_register
    if user_signed_in?
      redirect_to action: :step5_location
    end

    render locals: {is_user_logged_in: user_signed_in?, current_page: "step_4"}
  end
  
  def step5_location

    render locals: {is_user_logged_in: user_signed_in?, current_page: "step_5"}
  end
  
  def step6_review
    puts "steps_controller > step6_review"
    render locals: {is_user_logged_in: user_signed_in?, current_page: "step_6"}
  end
  
  def step7_payment

    render locals: {is_user_logged_in: user_signed_in?, current_page: "step_7"}
  end
  
  def step8_confirmation

    render locals: {is_user_logged_in: user_signed_in?, current_page: "step_8"}
  end
  
  private

    def get_drinks_data
      get_drinks_data_real
      # get_drinks_data_dummy
    end

    def get_speaker_data
      get_speaker_data_dummy
    end

    def get_drinks_data_file_contents
      _str_file_location = get_drinks_data_file_location
      _str_file_data = File.read _str_file_location
    end

    def get_drinks_format_file_contents
      _str_contents = get_drinks_data_file_contents
      _h_drinks = {}

      _arr_file_contents = _str_contents.split "\n"
      _int_drink_counter = 0
      _int_item_counter = 0

      _arr_file_contents.each do |str_line|
        puts "str_line: #{str_line}"
        _arr_line_contents = str_line.split ","
        

        if _arr_line_contents.length == 1

          _int_item_counter = 0
          _int_drink_counter += 1

          _h_drinks[_int_drink_counter] =  {
            id: _int_drink_counter,
            drink_type: str_line,
            items: Hash.new
          }
        else
          _int_item_counter += 1
          _arr_items_data = str_line.split ","

          puts "_h_drinks: #{_h_drinks}"

          _h_drinks[_int_drink_counter][:items][_int_item_counter] = {
            id: _int_item_counter,
            name: _arr_items_data[0],
            price: _arr_items_data[1],
            quantity: 0
          }
        end
      end
      
      _h_drinks
    end

    def get_drinks_data_real
      get_drinks_format_file_contents
    end

    def get_drinks_data_file_location
      Rails.root.join('public', 'uploads', 'drinks.csv')
    end

    def get_speaker_data_file_location
      Rails.root.join('public', 'uploads', 'speakers.csv')
    end

    def get_speaker_data_dummy
      {
        1 => {
          id: 1,
          name: "A",
          range: "0 - 10",
          price: 100,
          checked: false,
        },
        2 => {
          id: 2,
          name: "B",
          range: "10 - 20",
          price: 200,
          checked: false,
        },
        3 => {
          id: 3,
          name: "C",
          range: "20 - 30",
          price: 300,
          checked: false,
        }
      };
    end

end

__END__

0-10,A,100
10-20,B,200
20-30,C,300 
30-40,D,400

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/step3_total.html.erb
<!DOCTYPE html>
<html>

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Watts & Shots | Step3: total</title>


<style type="text/css">
    
    .div-background{
      width: 100vw;
      height: 100vh;
      background-image: linear-gradient(to bottom, var(--main-bg-color), var(--main-bg-color-gradient-stop));
      background-color: var(--main-bg-color);
      position: relative;
      padding: 0 0 50px 0;
      overflow: scroll;
    }

    .div-total-table-wrapper{
      display: flex;
      width: 100%;
      place-content: center;
    }

    table.tbl-total-table {
      opacity: 0.9;
      border-collapse: collapse;
      border-radius: 1em;
      overflow: hidden;
      max-width: 700px;
      width: calc(100% - 60px);
      box-sizing: border-box;
      margin: 30px;
    }

    #toc_3{
      text-align: center;
    }

    table.tbl-total-table {
      opacity: 0.9;
      border-collapse: collapse;
      border-radius: 1em;
      overflow: hidden;
      width: 100%;
    }

    .tbl-total-table *{
      text-align: center;
    }

    .tbl-total-table td {
      background: #e6e6e6;
    }

    .tbl-total-table th{
      background: #f5f5f5;
    }

    .tr-end-block td{
      background: #f5f5f5 !important;
    }
    

    .tbl-total-table th, .tbl-total-table td {
      padding: 0.7em;
      border-bottom: 2px solid white; 
    }

</style>


</head>





























<body>

  <div class="div-background">

    <!-- main partial #1 -->
      <%= render partial: 'components/steps_header', locals: {current_page: current_page, is_user_logged_in: is_user_logged_in} %>
    <!-- end -->



    <!-- div class="div-to-max"><div class="div-main-content" -->

        <h3 id="toc_3">Step 3: Totalling It Up</h3>

        <%= react_component 'TotalsTable' %>
        
      </div>
    </div>

    <!-- main partial #2 -->
    <%= render partial: 'components/steps_nav_next', locals: {
      go_back_class: '',
      go_back_url: steps_get_drinks_path,
      continue_url: steps_get_logged_in_path,
      continue_id: "a-step2-continue"
    } 
    
    %>
<!-- end -->

  </div>


<style>
a.disabled {
    pointer-events: none;
    color: gray;
}
</style>































<script type="text/javascript" src="/javascripts/site/common.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", init());

  function setup(){
    initHandlers();
    // setupTableData();
  }
  

  function init(){
    var objThis = this;
    
    document.addEventListener("DOMContentLoaded", () => {
      setup.call(objThis);
    })

    setTimeout(() =>{
      rerunSetupIfNeeded()
    }, 500);
  }

  function getPageData(){

    var objRetData = null;
    
    if (validatePage()){
      objRetData = {
        total: getTotalData()
      }
    }

    return objRetData;
  }

  function validatePage(){
    var strSpeaker;
    var boolIsValid = true;

    return boolIsValid;
  }

  function initHandlers(){
    // click continue
    document
      .getElementsByClassName("a-continue")[0]
      .addEventListener("click", handleClickContinue);
  }

  init();
</script>






































</body>

</html>

app/views/steps/step6_review.html.erb
<!DOCTYPE html>
<html>

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>step7_review</title>


<style type="text/css">
    .div-background{
      width: 100vw;
      background-image: linear-gradient(to bottom, var(--main-bg-color), var(--main-bg-color-gradient-stop));
      background-color: var(--main-bg-color);
      position: relative;
      padding: 0 0 100px 0;
      overflow: scroll;
    }

    .div-to-max{
      width: 100%;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: end;
      overflow: scroll;
    }

    .div-main-content{
      width: 60%;
    }

    #toc_3{
      text-align: center;
    }

    table.tbl-total-table {
      border-collapse: collapse;
      border-radius: 1em;
      overflow: hidden;
      width: 100%;
    }

    .tbl-total-table *{
      text-align: center;
    }

    .tbl-total-table td {
      background: #e6e6e6;
    }

    .tbl-total-table th{
      background: #f5f5f5;
    }

    .tr-end-block td{
      background: #f5f5f5 !important;
    }
    

    .tbl-total-table th, .tbl-total-table td {
      padding: 0.7em;
      border-bottom: 2px solid white; 
    }

</style>


</head>






















<body>

  <div class="div-background">

  <!-- ruby code --->

  <% if (defined? mode) && (mode == :edit_mode) %>

    <%= render partial: 'components/cookie_widget', locals: {cookie_string: cookie_string, event_id: event_id} %>

    <script type="text/javascript">
      var mode = "edit_mode";
    </script>
    
  
    <%= render partial: 'components/steps_header_lite', locals: {current_page: current_page, is_user_logged_in: is_user_logged_in} %>
    <%= render partial: 'components/steps_nav_edit', locals: {current_page: current_page, event_id: event_id} %>

  <% elsif (defined? mode) && (mode == :read_mode)%>

    <%= render partial: 'components/steps_header_lite', locals: {current_page: current_page, is_user_logged_in: is_user_logged_in} %>

  <% else %>

    <!-- main partial #1 -->
        <%= render partial: 'components/steps_header', locals: {current_page: current_page, is_user_logged_in: is_user_logged_in} %>
    <!-- end -->
  
  <% end %>
<!-- end -->



    <div class="div-to-max">
      <div class="div-main-content">


      <!-- ruby code --->
      <% if (defined? mode) && (mode == :delete_mode || mode == :edit_mode) %>
        <script text="text/javascript">
          var event_id = "<%= event_id %>";
          var foo = "bar";
        </script>

      <% end %>  
      <!-- end --->

      <!-- ruby code --->
            <% if !defined? mode %>
              <h3 id="toc_3">Step 6: Review</h3>
            <% elsif mode == :edit_mode %>
              <h3 id="toc_3">Step 6: Review and Save</h3>
            <% elsif mode == :delete_mode %>
              <h3 id="toc_3">Cancel Event</h3>
            <% elsif mode == :read_mode %>
              <h3 id="toc_3">View Event</h3>
            <% end %>
      <!-- end --->

      <!-- ruby code --->
            <% if (defined? mode) && (mode == :read_mode) %> 

              <%= render partial: 'components/cookie_widget', locals: {cookie_string: cookie_string, event_id: event_id} %>

              <script>
                var mode = "read_mode";
              </script>

            <% end %>
      <!-- end --->

      <!-- ruby code --->
            <% if (defined? mode) && (mode == :edit_mode)  %>

              <%= render partial: 'components/cookie_widget', locals: {event_id: event_id} %>

              

              <script type="text/javascript">
                var mode = "edit_mode";
              </script>
              
            <% end %>
      <!-- end --->

      <h3 id="toc_4">Order Summary</h3>

      <!-- ruby code --->
            <% if !defined? mode %>
              <p>This is your order summary, showing you how much your order would cost:</p>
            <% end %>
      <!-- end --->

          <%= react_component 'TotalsTable' %>
          <p><br/></p>

          <h4 id="toc_8">Date</h4>

          <p><span id="spn-time"></span></p>

          <h4 id="toc_9">Location</h4>

          <p><span id="spn-location"></span></p>

          <h4 id="toc_9">Setting</h4>

          <p><span id="spn-setting"></span></p>

          <p><br></p>













          <!-- ruby code --->

          <% if defined? mode && mode == :delete_mode %>
    
            <h3 id="toc_8">Our Refund Policy</h3>
    
            <ol>
            <li><p>Cancellation MUST be More than 48 hours before the booked time/date, or they will lose their deposit.</p></li>
            <li><p>Assuming the cancellation is more than 48 hours in advance, then a 12% handling fee will be deducted and the balance refunded.</p></li>
            </ol>
    
          <% end %>
    
    <!-- ruby code --->
    
    
    
            <% if (defined? mode) && (mode == :edit_mode) %>
    
            <script type="text/javascript" src="/javascripts/site/common.js"></script>
    
            <%= form_with(model: @event) do |f| %>
            <% end %>
    
            <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
    
            <script>
    
            function setupEventHandlers(){
              console.log("setupEventHandlers");
    
              var objThis = this;
    
              $("#a-update_event")
                .unbind("click")
                .click(handleClickContinueWSubmit.bind(objThis));
            }
    
            function handleClickContinueWSubmit(objEvent){
    
              console.log("handleClickContinueWSubmit");
    
              patchToBackend();
              objEvent.preventDefault();
            }
    
            function patchToBackend(){
    
              console.log("patchToBackend | alpha");
          
              var strUrl = `/event/update/${event_id}`;
              var objData = {
                authenticity_token: window._token,
                data: getCookieObj()
              };
              var strObjData = JSON.stringify(objData);
          
              fetch(strUrl,
              {
                headers: {
                  'Accept': 'application/json',
                  'Content-Type': 'application/json'
                },
                method: 'PATCH',
                body: strObjData
              })
              .then((resp) => resp.json())
              .then((data) => {
                console.log(data);
                redirectToProfilePage();
              })
            }
    
            function redirectToProfilePage(){
              var strUrl = "/user/profile_page";
    
              window.location.replace(strUrl);
            }
    
            function setup(){
              setupEventHandlers();
            }
    
            function init(){
              var objThis = this;
              
              document.addEventListener("DOMContentLoaded", () => {
                setup.call(objThis);
              })
    
              setTimeout(rerunSetupIfNeeded, 500);
            }
    
            // init();
            setTimeout(setupEventHandlers, 1000);
    
            </script>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
          <% elsif (defined? mode) && (mode == :delete_mode) %>
    
            <script type="text/javascript" src="/javascripts/site/common.js"></script>
    
            <%= form_with(model: @event) do |f| %>
            <% end %>
    
            <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
    
            <!-- h3 id="toc_9">Confirm Event Cancellation</h3>
            <ul>
            <li><%= link_to "Delete", steps_get_confirmation_path, id: "a-delete_event" %></li>
            </ul -->
    
            <script>
    
            // bookmark
            function setupEventHandlers(){
              console.log("setupEventHandlers");
    
              var objThis = this;
    
              $("#a-delete_event")
                .unbind("click")
                .click(handleClickToDelete.bind(objThis));
            }
    
            function handleClickToDelete(objEvent){
    
              console.log("handleClickToDelete");
    
              deleteToBackend();
              objEvent.preventDefault();
            }
    
            function deleteToBackend(){
    
              console.log("deleteToBackend | alpha");
          
              var strUrl = `/event/delete/${event_id}`;
              var objData = {
                authenticity_token: window._token
              };
              var strObjData = JSON.stringify(objData);
          
              fetch(strUrl,
              {
                headers: {
                  'Accept': 'application/json',
                  'Content-Type': 'application/json'
                },
                method: 'DELETE',
                body: strObjData
              })
              .then((resp) => resp.json())
              .then((data) => {
                console.log(data);
                redirectToProfilePage();
              })
            }
    
            function redirectToProfilePage(){
              var strUrl = "/user/profile_page";
    
              window.location.replace(strUrl);
            }
    
            function setup(){
              setupEventHandlers();
            }
    
            function init(){
              var objThis = this;
              
              document.addEventListener("DOMContentLoaded", () => {
                setup.call(objThis);
              })
    
              setTimeout(rerunSetupIfNeeded, 500);
            }
    
            // init();
            setTimeout(setupEventHandlers, 1000);
    
            </script>
          <% end %>
    
    <!-- end --->









      </div>
    </div>

    <% if (!defined? mode) || (mode != :edit_mode) || ((mode != :read_mode) && (mode != :delete_mode))%>

    <% 
    
    if (defined? mode) && (mode == :edit_mode) 
      _continue_url = "/event/update/#{event_id}/8"
      _go_back_url = "/event/update/#{event_id}/5"
      _partial = 'components/steps_nav_next_review_page'
      _event_id = event_id
    else
      _go_back_url = steps_get_location_path
      _continue_url = steps_get_payment_path
      _partial = 'components/steps_nav_next'
      _event_id = -1
    end
    
  %>

    <% if (!defined? mode) || (mode != :read_mode)%>

      <!-- main partial #2 -->
      <%= render partial: _partial, locals: {
        go_back_class: '',
        go_back_url: _go_back_url,
        continue_url: _continue_url,
        continue_id: "a-step2-continue",
        event_id: _event_id
      } 
      
      %>

    <% end %>

    <% elsif mode == :delete_mode %>

      <style>
        .btn-standard{
          background-color: #3D5AEF;
          padding: 10px 40px;
          border-radius: 25px;
          color: #eee;
          box-shadow: 0 3px 5px black;
          text-align: center;
        }

        #div-delete-container{
          width: 100%;
          height: 100px;
          display: flex;
          flex-direction: row;
          justify-content: center;
          align-items: center;
          position: absolute;
          bottom: 0;
          left: 0;
        }
      </style>
      <div id="div-delete-container">
      <%= link_to "Delete", steps_get_confirmation_path, id: "a-delete_event", class: 'btn btn-standard'  %></li>
      </div>

      <!--  working -->
      <% elsif mode == :edit_mode %>

      <style>
        .btn-standard{
          background-color: #3D5AEF;
          padding: 10px 40px;
          border-radius: 25px;
          color: #eee;
          box-shadow: 0 3px 5px black;
          text-align: center;
        }

        #div-delete-container{
          width: 100%;
          height: 100px;
          display: flex;
          flex-direction: row;
          justify-content: space-between;
          align-items: center;
          position: absolute;
          bottom: 0;
          left: 0;
        }
      </style>

      <div id="div-delete-container">
      <%= link_to "Delete", steps_get_confirmation_path, id: "a-delete_event", class: 'btn btn-standard'  %></li>
      </div>



    <% end %>
    
    
<!-- end -->

  </div>


<style>
a.disabled {
    pointer-events: none;
    color: gray;
}
</style>































<script type="text/javascript" src="/javascripts/site/common.js"></script>
<script>


  function setup(){
    setupTimeAndLocation();
  }

  function init(){
    var objThis = this;
    
    document.addEventListener("DOMContentLoaded", () => {
      setup.call(objThis);
    })

    setTimeout(rerunSetupIfNeeded(), 500);
  }

  init();

</script>



















































</body>

</html>

app/views/steps/step8_confirmation.html.erb
<!DOCTYPE html>
<html>

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>step8 | confirmation</title>


<style type="text/css">
    
.div-background{
  width: 100vw;
  height: 80vw;
  min-height: 800px;
  max-height: 900px;
  background-image: linear-gradient(to bottom, var(--main-bg-color), var(--main-bg-color-gradient-stop));
  background-color: var(--main-bg-color);
  position: relative;
  overflow: scroll;
}

    .div-to-max{
      width: 100%;
      height: 43vw;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: end;
      overflow: scroll;
    }

    .div-main-content{
      width: 60%;
    }

    #toc_3{
      text-align: center;
    }

    table.tbl-total-table {
      border-collapse: collapse;
      border-radius: 1em;
      overflow: hidden;
      width: 100%;
    }

    .tbl-total-table *{
      text-align: center;
    }

    .tbl-total-table td {
      background: #e6e6e6;
    }

    .tbl-total-table th{
      background: #f5f5f5;
    }

    .tr-end-block td{
      background: #f5f5f5 !important;
    }
    

    .tbl-total-table th, .tbl-total-table td {
      padding: 0.7em;
      border-bottom: 2px solid white; 
    }

</style>


</head>






















<body>

  <div class="div-background">

  <!-- ruby code --->

  <% if (defined? mode) && (mode == :edit_mode) %>

    <%= render partial: 'components/cookie_widget', locals: {cookie_string: cookie_string, event_id: event_id} %>

    <script type="text/javascript">
      var mode = "edit_mode";
    </script>
    
  
    <%= render partial: 'components/steps_header_lite', locals: {current_page: current_page, is_user_logged_in: is_user_logged_in} %>
    <% # render partial: 'components/steps_nav_edit', locals: {current_page: current_page, event_id: event_id} %>



  <% else %>

    <!-- main partial #1 -->
        <%= render partial: 'components/steps_header', locals: {current_page: current_page, is_user_logged_in: is_user_logged_in} %>
    <!-- end -->
  
  <% end %>
<!-- end -->


    <div class="div-to-max">
      <div class="div-main-content">


      
      
      <h3 id="toc_3">Step 8: Confirmation</h3>

      <!-- ruby code --->
            <% if (defined? mode) && (mode == :read_mode) %> 

              <%= render partial: 'components/cookie_widget', locals: {cookie_string: cookie_string, event_id: event_id} %>

              <script>
                var mode = "read_mode";
              </script>

            <% end %>
      <!-- end --->

      <!-- ruby code --->
            <% if (defined? mode) && (mode == :edit_mode)  %>

              <%= render partial: 'components/cookie_widget', locals: {event_id: event_id} %>

              <script type="text/javascript">
                var mode = "edit_mode";
              </script>
              
            <% end %>
      <!-- end --->

      <h3 id="toc_4">Order Summary</h3>

      <!-- ruby code --->
            <% if !defined? mode %>
              <p>This is your order summary, showing you how much your order would cost:</p>
            <% end %>
      <!-- end --->

          <%= react_component 'TotalsTable' %>
          <p><br/></p>

          <h4 id="toc_8">Time</h4>

          <p><span id="spn-time">31st December, 2018</span></p>

          <h4 id="toc_9">Location</h4>

          <p><span id="spn-location"></span></p>

          <h4 id="toc_9">Setting</h4>

          <p><span id="spn-setting"></span></p>

          <p><br></p>














          <!-- ruby code --->

          <% if !defined? mode || mode == :delete_mode %>
    
            <h3 id="toc_8">Our Refund Policy</h3>
    
            <ol>
            <li><p>Cancellation MUST be More than 48 hours before the booked time/date, or they will lose their deposit.</p></li>
            <li><p>Assuming the cancellation is more than 48 hours in advance, then a 12% handling fee will be deducted and the balance refunded.</p></li>
            </ol>
    
          <% end %>
    
    <!-- ruby code --->
    
    
    
            <% if (defined? mode) && (mode == :edit_mode) %>
    
            <script type="text/javascript" src="/javascripts/site/common.js"></script>
    
            <%= form_with(model: @event) do |f| %>
            <% end %>
    
            <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
          <% elsif (defined? mode) && (mode == :delete_mode) %>
    
            <script type="text/javascript" src="/javascripts/site/common.js"></script>
    
            <%= form_with(model: @event) do |f| %>
            <% end %>
    
            <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
    
            <h3 id="toc_9">Confirm Event Cancellation</h3>
            <ul>
            <li><%= link_to "Delete", steps_get_confirmation_path, id: "a-delete_event" %></li>
            </ul>
    
          <% end %>
    
    <!-- end -->




      </div>
    </div>

<!-- end -->

  </div>


<style>
a.disabled {
    pointer-events: none;
    color: gray;
}
</style>































<script type="text/javascript" src="/javascripts/site/common.js"></script>
<script>


  function setup(){
    setupTimeAndLocation();
  }

  function init(){
    var objThis = this;
    
    document.addEventListener("DOMContentLoaded", () => {
      setup.call(objThis);
    })

    setTimeout(rerunSetupIfNeeded(), 500);
  }

  init();

</script>



















































</body>

</html>