config/routes.rb
Rails.application.routes.draw do
  
  get 'about_us', to: "about_us#show"
  
  # upload
  match 'admin/drinks', via: [:get, :post]
  match 'admin/speakers', via: [:get, :post]


  # event
  post 'event/create'

  get 'event/update/:id/:step', to: "event#update_get"
  patch 'event/update/:id',     to: "event#update_patch"

  get 'event/view/:id',         to: "event#read"
  delete 'event/delete/:id',    to: "event#delete"

  post 'event/payment',        to: "event#payment"

  # user
  get 'user/cancel_event/:id', to: "user#cancel_event"
  get 'user/profile_page', as: :get_profile




  # steps
  namespace :steps do    
    # get 'step1_speakers', as: :get_speakers
    match 'step1_speakers', as: :get_speakers, via: [:get, :post]

    get 'step2_drinks', as: :get_drinks
    get 'step3_total', as: :get_total
    get 'step5_location', as: :get_location
    get 'step6_review', as: :get_review
    get 'step7_payment', as: :get_payment
    get 'step8_confirmation', as: :get_confirmation
  end

  root 'application#homepage'
  
  # devise routes
  devise_for :users, path: '', 
    controllers: { registrations: 'auth/registrations' }, 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'logout', 
      password: 'password', 
      confirmation: 'confirmation', 
      unlock: 'unlock', 
      registration: 'register', 
      sign_up: 'join' }
    
  
  # add a GET logout
  devise_scope :user do
    get 'logout', to: 'devise/sessions#destroy'
    get 'profile/edit', to: 'devise/registrations#edit', as: :get_profile_edit
    get 'steps/step4_login_register'=> 'auth/register#step4_login_register', as: :steps_get_logged_in
    post 'steps/step4_login'=> 'auth/login#create', as: :post_auth_login
    post 'steps/step4_register'=> 'auth/register#create', as: :post_auth_register
    post 'password-level'=> 'auth/register#password_meter', as: :post_auth_password_level
        
    # redirection links alias
    get 'steps/step4_login'=> 'auth/register#step4_login_register'
    get 'steps/step4_register'=> 'auth/register#step4_login_register'
  end
  
  # redirect all missing path to home
  get "*path", to: redirect('/')

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def homepage

    puts "ApplicationController > homepage"

    render locals: {is_user_logged_in: user_signed_in?}
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone])
  end
  
  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
  
  def authorize_admin
    redirect_to root_url unless current_user.is_admin
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/homepage.html.erb
<!DOCTYPE html>
<html>

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>homepage</title>
<style>

    .p-blurb{
      font-size: 1.5em;
      color: #eee;
      margin: 0 20px;
    }

    .div-page-canvas{
      background-image: linear-gradient(to bottom, #3D59ED, rgba(255, 255, 255, 0));
      display: flex;
      flex-direction: row;
      justify-content: center;
      align-items: center;
    }

    .fill-page{
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      overflow: scroll;
    }

    .div-bkgd-image{
      background-image: url('./images/homepage-bkdg.jpeg');
      background-repeat: no-repeat;
      background-size: cover;
      bottom: 0 !important;
    }

    .div-page-container{
      width: 100vw;
      height: 100vh;
      padding: 0;
      margin: 0;
      position: relative;
    }

    body{
      padding: 0;
      margin: 0;
    }

    .div-panel-wrapper{
      width: 500px;
      height: 450px;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      align-items: center;
    }

    .btn-standard{
      background-color: #3D5AEF;
      padding: 10px 40px;
      border-radius: 25px;
      color: #eee;
      box-shadow: 0 3px 5px black;  
    }
  </style>
 
</head>


























<%= stylesheet_link_tag "/stylesheets/homepage.scss" %>






<body>
  <div class="div-page-container div-page-container-homepage">
    <div class="div-bkgd-image fill-page"></div>
    <div class="div-page-canvas fill-page">
      <div position="relative" class="div-panel-wrapper">

      <img src="/images/wns.logo.png">

      <p class="p-blurb">Your one-stop shop for all your party needs</p>

      <%= link_to "Start planning", steps_get_speakers_path, class: 'btn btn-standard' %> 

      <% if is_user_logged_in %>
          <%= link_to "Your profile", get_profile_path, class: 'btn btn-standard' %>
      <% else %>
          <%= link_to "Login", '/login', class: 'btn btn-standard' %>
      <% end %>

      </ul>
      </div>
    </div>
  </div>
























<script type="text/javascript" src="/javascripts/site/common.js"></script>
<script>

  
function setup(){
  console.log("step 0 > setup");  

  eraseCookie();
  toggleHasRunSetup();
}

function init(){
  var objThis = this;
  
  document.addEventListener("DOMContentLoaded", () => {
    setup.call(objThis);
  })

  setTimeout(() =>{
    rerunSetupIfNeeded()
  }, 500);
}


init();

</script>




</body>

</html>